Главная страница. Попытка №2
4irik/twitter-demo-frontend pull request #1
Opened 2018-06-20 13:59 UTC by 4irik

2018-06-25 16:09 UTC, imevro requested changes

2018-06-25 16:09 UTC, evgenyrodionov commented on src/App.js
> +function ProfilePage() {
я бы вынес в отдельную директорию всё-таки

2018-06-25 16:09 UTC, evgenyrodionov commented on src/App.js
> +const UserProfile = {
camelCase

2018-06-25 16:09 UTC, evgenyrodionov commented on src/Cover/index.js
> +  @media (min-width: 1820px) {
чё-т как-то хз

2018-06-25 16:09 UTC, evgenyrodionov commented on src/Cover/index.js
> +  @media (min-width: 1820px) {
max-height мб чтобы такую портянку не писать?

2018-06-25 16:09 UTC, evgenyrodionov commented on src/Header/index.js
> +  margin-left: -27px;
баг же явный

2018-06-25 16:09 UTC, evgenyrodionov commented on src/Header/index.js
> +    url: "/notifications",
верстку лучше не программировать

2018-06-25 16:09 UTC, evgenyrodionov commented on src/Header/index.js
> +    url: "/notifications",
это статичные адресы и им подходит обычный жсх

2018-06-25 16:09 UTC, evgenyrodionov commented on src/Header/index.js
> +          <div className="col-xs-6">
сетка вообще тут не нужна

2018-06-25 16:09 UTC, evgenyrodionov commented on src/Post/Actions.js
> +    let icon;
нахуй мутабельность

2018-06-25 16:09 UTC, evgenyrodionov commented on src/Post/Card.js
> +  return !props.card ? (
зачем? делай нормальный if (props.card)

2018-06-25 16:09 UTC, evgenyrodionov commented on src/Post/Pin.js
> +  if (!props.isPinned) {
пиши условия при которых код сработает, а не наоборот

ну и пустую строку возвращат ьне надо

2018-06-25 16:09 UTC, evgenyrodionov commented on src/Post/Tweet.js
> +`;
какой-то полный треш

2018-06-25 16:09 UTC, evgenyrodionov commented on src/Post/Tweet.js
> +  return props.img ? (
Почему ты не можешь вынести это в нормальный компонент?

2018-06-25 16:09 UTC, evgenyrodionov commented on src/Post/index.js
> +    autor: Autors[0],
опеатка же

2018-06-25 16:09 UTC, evgenyrodionov commented on src/Post/index.js
> +      "We’ve made so1me more resources for all you wonderful " +
давай без вот этого вот, не 2001 всё же

2018-06-25 16:52 UTC, 4irik commented on src/Header/index.js
> +  margin-left: -27px;
Это кнопка поиска в заголовке, отрицательный отступ нужен для того чтобы она была внутри поля поиска

2018-06-25 16:56 UTC, 4irik commented on src/Post/Actions.js
> +    let icon;
Предлагаешь в при вызове указывать конкретную иконку?

2018-06-27 18:17 UTC, 4irik commented on src/Post/Pin.js
> +  if (!props.isPinned) {
Если ничего не возвращать, то получим ошибку:

![2018-06-27-231104_1920x1080_scrot](https://user-images.githubusercontent.com/2486299/41991618-8210cb4c-7a5f-11e8-97e7-7c0549626187.png)

так что возвращать что-то надо, хотя бы `null`.

Если же проверять на соответствие условию, то получим большое число строк внутри блока `if` и всего одну строку вне него. По-моему читать такое сложнее.

```jsx
export default props => {
  if (props.isPinned) {
    return (
      <Context>
        <ContextIcon src={iconPinned} alt="" />
        <ContextHint>Pinned Tweet</ContextHint>
      </Context>
    );
  }

  return null;
};
```

2018-06-27 19:02 UTC, 4irik commented on src/Post/Tweet.js
> +`;
правки чуть выше этой области

2018-07-06 07:23 UTC, merged